Add an new cat
charpeni/svelte-example pull request #4
Opened 2016-12-11 10:40 UTC by guinetn

Use the 'Add' button or press [Enter]

2016-12-11 16:04 UTC, charpeni requested changes
Thank you for your contribution.

Unfortunately, it does not seem to work properly. I can add a new cat to the list, but it seems rendered many cycles after and I got this error :

`main.js:280 Uncaught TypeError: cat.set is not a function(…)`

2016-12-11 16:04 UTC, charpeni commented on src/components/CatList.html
> +  import Cat from '../components/Cat.html';
Was there an issue with this import ?

2016-12-13 19:46 UTC, guinetn commented on src/components/CatList.html
> +  import Cat from '../components/Cat.html';
Hi, I didn't get any error. Wich browser are you using?
I publish it here: https://github.com/guinetn/svelte-example

This has no impact but first is better:
-  import Cat from './Cat.html';
+  import Cat from '../components/Cat.html';

2016-12-14 22:28 UTC, charpeni commented on src/components/CatList.html
> +  import Cat from '../components/Cat.html';
@guinetn On chrome, latest version.

2017-10-17 17:38 UTC, charpeni submitted a review, later dismissed

2017-10-17 17:43 UTC, charpeni approved these changes

2017-10-17 17:43 UTC, merged